### ISSUE TITLE
sampleQC not working

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#233] opened 2021-07-18 22:53 UTC
Hi,
I'm getting this error in snakemake sampleQC:
```
Structuring dependencies...
Dependencies file generated at: /tmp/tmp0qhwfbfs

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    QC/UDP.md
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_QC_Datasets.md
```

**Comment by nickhsmith** [comment] 2021-07-19 18:54
Could you please let us know which version of drop you are using? and how you ran the pipeline, did you call all modules or just MAE? 
`drop --version`

Additionally could you please send us your config file, and the entirety of the logging information. It's hard to diagnose what the problem may be from just this snippet. Thanks

**Comment by gevro** [comment] 2021-07-20 04:34
drop --version
```
drop, version 1.0.5
```

How I ran sampleQC (I ran this after running aberrantExpression and aberrantSplicing. I have not yet run mae):
```
snakemake sampleQC --cores 2
```

Error/output
```
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmplncxvu0h

Unlocking working directory.
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmp0qhwfbfs

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    QC/UDP.md
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_QC_Datasets.md
```

config.yaml
```
ProjectTitle: Test
root: /gpfs/scratch/drop/root            # root directory of all intermediate output
htmlOutputPath: /gpfs/scratch/drop/htmlOutput  # path for HTML rendered reports
indexWithFolderName: true # whether the root base name should be part of the index name

hpoFile: null  # if null, downloads it from webserver

sampleAnnotation: /gpfs/scratch/drop/samples.tsv

geneAnnotation:
# multiple annotations with custom names are possible
# <annotation_name> : <path to gencode v29 annotation>
  v32: /gpfs/data/reference-files/GRCh38_gencode-STAR/gencode.v32.primary_assembly.annotation.gtf

genomeAssembly: hg38  # either hg19 or hg38
genome: /gpfs/data/reference-files/GRCh38_gencode-STAR/GRCh38_primary_assembly_genome.fa

exportCounts:
  # specify which gene annotations to include and which 
  # groups to exclude when exporting counts
  geneAnnotations:
  - v32
  excludeGroups:
  - null

aberrantExpression:
  groups: 
  - GTEX100
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: 0.05
  zScoreCutoff: 0
  maxTestedDimensionProportion: 3

aberrantSplicing:
  groups:
  - GTEX100
  recount: false
  longRead: false
  keepNonStandardChrs: false
  filter: true
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 0.05
  zScoreCutoff: 0
  deltaPsiCutoff: 0.3
  maxTestedDimensionProportion: 6

mae:
  groups:
  - UDP
  genome: /gpfs/data/reference-files/GRCh38_gencode-STAR/GRCh38_primary_assembly_genome.fa
  gatkIgnoreHeaderCheck: true
  padjCutoff: .05
  allelicRatioCutoff: 0.8
  addAF: true
  maxAF: .001
  maxVarFreqCohort: .05
  # VCF-BAM matching
  qcVcf: /gpfs/data/reference-files/hg38-gatk/qc_vcf_1000G.hg38.vcf.gz       # path to common variant file e.g. qc_vcf_1000G.vcf.gz
  qcGroups:
  - UDP

tools:
  gatkCmd: gatk
  bcftoolsCmd: bcftools
  samtoolsCmd: samtools
```

Note, I get a similar error when running mae:
```
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmplef56382

Unlocking working directory.
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmpzk0vb3gx

Building DAG of jobs...
WorkflowError:
WorkflowError:
    MissingInputException: Missing input files for rule markdown:
    MAE/UDP--v32_results.md
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_MAE_Datasets.md
```

**Comment by mumichae** [comment] 2021-07-20 17:26
Could you try
```
drop update 
```
And run the pipeline again?

**Comment by gevro** [comment] 2021-07-20 20:23
I still get the same error:
```
Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/evrong01/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    QC/UDP.md
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_QC_Datasets.md
```

**Comment by mumichae** [comment] 2021-07-20 20:24
Have you by any chance added an R script? E.g. `QC/URP.R`?

**Comment by gevro** [comment] 2021-07-20 20:34
I'm not sure what you mean, but have not added any R scripts.
Also, here are the files in the QC directory. There is no URP.R file.

```
drop]$ ls ./Scripts/MonoallelicExpression/pipeline/QC
create_matrix_dna_rna_cor.R  Datasets.R  deseq_qc.R  DNA_RNA_matrix_plot.R
```

**Comment by mumichae** [comment] 2021-07-20 20:52
OK, then that's not it. In the `mae_allelicCounts` rule there is an error in one of input functions. Could you check in your config and sample annotation that all MAE-specific files are provided as per documentation? Specifically, is the `genome` key in the proper location and are you using the `GENOME` column in the sample annotation? @nickhsmith Is that column mandatory or will we get an error if it isn't provided?

Also @gevro, please consider using the `--debug` option to your snakemake command, so that we can get a more verbose error message.

**Comment by nickhsmith** [comment] 2021-07-20 21:08
The config seems to be built in a generally consistent way. The genome variable is defined twice (once in the MAE section, and once globally) but they're the same, and it is using the one defined in MAE. We are hoping to publish a new version of DROP early Wednesday, which is full of changes. Hopefully this will alleviate the problem. Sorry for the uncertainty in our answers.

Essentially we use a package called wBuild to search through the Scripts directory recursively and build html files so that all of the analysis is easier to search through, and it looks for html files that need to be build and makes sure they have the corresponding markdown file as a descriptor. In your case, it seems to think that QC/UDP.md should exist, but it doesn't which is confusing.

would you mind also sharing your sample annotation table? The other thing I'd be curious about is if you ran
`snakemake /gpfs/scratch/drop/root/processed_data/mae/allelic_counts/QC--UDP-1003_RNA.csv.gz --cores 1` 

Do you still get the error? I'm hoping to bypass the issue by asking the pipeline to only try to build the one QC file, and see if that works

**Comment by gevro** [comment] 2021-07-20 21:17
1) I am not using the GENOME column in the sample annotation.
2) Here is an example of a few samples from the sample table:
```
RNA_ID  DNA_ID  DROP_GROUP      RNA_BAM_FILE    PAIRED_END      STRAND  COUNT_MODE      COUNT_OVERLAPS  DNA_VCF_FILE    GENE_COUNTS_FILE        GENE_ANNOTATION
UDP-1703_RNA    UDP-1703_exome  GTEX100,GTEXALL,UDP     /gpfs/scratch/UDP_RNA-seq/UDP-1703_RNA.bam     TRUE    no      IntersectionStrict      TRUE    /gpfs/data/NYU-UDP/variants/UDP-1700/WES.SNVINDEL/UDP-1703_exome.vcf.gz               
UDP-1903_RNA    UDP-1903_genome GTEX100,GTEXALL,UDP     /gpfs/scratch/UDP_RNA-seq/UDP-1903_RNA.bam     TRUE    no      IntersectionStrict      TRUE    /gpfs/data/NYU-UDP/variants/UDP-1900/WGS.SNVINDEL/UDP-1900_genome.vcf.gz              
UDP-3503_RNA    UDP-3503_exome  GTEX100,GTEXALL,UDP     /gpfs/scratch/UDP_RNA-seq/UDP-3503_RNA.bam     TRUE    no      IntersectionStrict      TRUE    /gpfs/data/NYU-UDP/variants/UDP-3500/WES.SNVINDEL/UDP-3500-blood_exome.jointHC.refined.filtered.vcf.gz 
```

3) Note that 2 of the samples in my sample table do not have entries for DNA_VCF_FILE. This is because I only have RNA-seq for those samples, but not DNA-seq. Could this be the problem?

4) I tried your suggested script for sample QC of just 1 sample and got this output:
```
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmplmazpqng

Building DAG of jobs...
MissingRuleException:
No rule to produce drop/root/processed_data/mae/allelic_counts/QC--UDP-1003_RNA.csv.gz (if you use input functions make sure that they don't raise unexpected exceptions).
```

5) If I upgrade to your new version of DROP, do I need to rerun aberrantExpression and aberrantSplicing, or can I skip straight to sampleQC and mae? How do I update the drop folder to the new version without having to rerun everything from scratch?

**Comment by nickhsmith** [comment] 2021-07-20 21:41
1. that's not a problem the GENOME column is only if you want to pick and choose which reference fasta to use. 
2. thank you, it seems to be set up correctly.
3. you need to have DNA-vcfs for MAE, but as long as these files are not marked as `UDP` in the DROP_GROUP column it shouldn't be an issue
4. did you type the full path into ` snakemake /gpfs/scratch/drop/root/processed_data/mae/allelic_counts/QC--UDP-1003_RNA.csv.gz --cores 1` ? the way we build the files requires the full path, and I noticed that the error in number 4 was missing the first part `/gpfs/scratch/` which may not accurately describe the behavior. Could you also confirm that the path I wrote is indeed where the files are being generated?
5. DROP update won't update files that aren't changed, but you can run

`snakemake aberrantExpression --touch -F` which will touch any and all associated aberrantExpression files which means you shouldn't have to worry about redoing them after the update. You should do the same for aberrantSplicing too.

Is it right that you didn't have any issues with the aberrantExpression or aberrantSplicing pipelines? Sorry for the confusion, and we will try our best to help you solve the issue.

**Comment by gevro** [comment] 2021-07-20 23:17
4. I reran with the full path, and now I am getting this error:
```
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmpop8vi6ef

Building DAG of jobs...
WorkflowError in line 55 of /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile:
Function did not return str or list of str.
```

Also, I can confirm the path you wrote is where the files are being generated.

5. I am not sure what you mean by "DROP update won't update files that aren't changed". What does that mean exactly?
 - Also, what does "snakemake aberrantExpression --touch -F" do exactly? Will that cause drop to redo the aberrantExpression pipeline that was done for 1.0.5 after upgrading to 1.0.6? Or does it mean that drop will NOT redo the aberrantExpression pipeline that was done for 1.0.5 after upgrading to 1.0.6? What is the advantage/disadvantage of doing 'snamekae aberrantExpression --touch -F"?

aberrantExpression and aberrantSplicing pipelines are working fine.

**Comment by nickhsmith** [comment] 2021-07-20 23:23
Drop update will only change files that are different. So between updates
files that are unchanged won't trigger a rerun. The touch command goes
through and systematically Updates each files timestamp that should exist
after running the pipeline. So that the next time you run snakemake it
won't want to regenerate those files. This will make it so you snakemake
won't trigger a rerun of aberrant expression or splicing.

**Comment by gevro** [comment] 2021-07-21 00:11
Not sure I understand.
"Drop update will only change files that are different." --> This means that NOT doing "touch" will cause the new version of drop to NOT touch the files.

"The touch command goes
through and systematically Updates each files timestamp that should exist
after running the pipeline. So that the next time you run snakemake it
won't want to regenerate those files. This will make it so you snakemake
won't trigger a rerun of aberrant expression or splicing."
--> This means that doing "touch" will cause the new version of drop to NOT touch the files.

Does doing "touch" cause the new version of drop to rerun the pipelines or not to rerun the pipelines?
Does not doing "touch" cause the new version of drop to rerun the pipelines or not to rerun the pipelines?

**Comment by nickhsmith** [comment] 2021-07-21 01:32
Snakemake runs by connecting a series of inputs and outputs, if the output
is older than the input, it must be because the input has changed and as a
result potentially the output will be different, and it wants to rerun that
process such that the new output file is more recent than than the input.

So if I have files A, B, and C in DROP and A is in aberrantExpression, B is
in aberrantSplicing, and C is in MAE. In the new version I change file A
into AA which is a quality of life change. The analysis is the same, but
now has is easier to use as a developer. If I run 'drop update' my local
version of A will update to AA, along with a new timestamp, but files B and
C won't change or have a new timestamp.

If I run 'snakemake' DROP says I need to rerun any process downstream of A
in the aberrantExpression pipeline because now AA is different and is newer
than the output files, and this change may affect the results, but because
the pipelines for aberrantSplicing and MAE are based on the unchanged files
B and C. These modules won't be affected.

However, if I run 'snakemake --touch' I am forcing snakemake to go through
all of the downstream processes of AA, and say if that file exists update
the timestamp information such that the output file is now more recent than
the input. This way the original premise of snakemake of connecting inputs
and outputs follows the logical chronological order that the outputs and
downstream analysis are newer than the inputs that are required to generate
them.

touch, just means that it is updating the timestamp. The files aren't
different, the internal data is unchanged, only the metadata concerning
their time.

So the next time you run 'snakemake' it will see that the chronological
order is now in the logical and correct order (input is older than output)
and won't rerun. Without running 'snakemake --touch' because the new update
does update A -> AA that snakemake will want to redo this analysis, which
you don't want to do.

'drop update' is important because it does fix bugs, add new features, and
improved logging information. 'snakemake --touch' is to avoid rerunning
analysis.

Does that make more sense? If not, you can also read a bit more about it here:
https://gagneurlab-drop.readthedocs.io/en/latest/pipeline.html?highlight=touch#skipping-recomputation-of-files

As for your issue, the new update does make the MAE pipeline more robust so
are hoping that this update will solve your issue.

**Comment by gevro** [comment] 2021-07-21 13:05
Great thanks. I will actually just try the new DROP 1.1.0 for everything from the beginning for all the pipelines.

**Comment by gevro** [comment] 2021-07-26 03:28
Hello. I tried again with DROP 1.1.0, but I'm getting the same error for sampleQC:
```
UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmp8ymob91z

Unlocking working directory.
UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmpplz3cqcn

Building DAG of jobs...
WorkflowError:
WorkflowError:
    MissingInputException: Missing input files for rule markdown:
    MonoallelicExpression/QC/UDP.md
    WorkflowError (rule mae_allelicCounts, line 108, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_QC_Datasets.md
```

**Comment by gevro** [comment] 2021-07-26 03:30
Also mae is giving a similar error, same as before upgrading to DROP 1.1.0:
```
WorkflowError:
WorkflowError:
    WorkflowError (rule mae_allelicCounts, line 108, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    MonoallelicExpression/UDP--v32_results.md
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_MAE_Datasets.md
```

**Comment by nickhsmith** [comment] 2021-07-26 08:02
I'm sorry for this problem, One thing I'm confused about is the sample params keep being updated, are you constantly changing your sample_annotation file? If you run it twice back to back (each getting errors) do you still see this warning both times?

This warning "UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation" should only happen when you update the sample_annotation.tsv file. Maybe there are problems there?

If you want, we could try to set up an email conversation (smith@in.tum.de) to try to work through exactly what is happening. Again, thank you for your patience

**Comment by nickhsmith** [comment] 2021-07-26 12:54
In the meantime, you are using the new drop version right? This is not available on conda yet, but could be installed using
`pip install git+https://github.com/gagneurlab/drop.git` and confirmed using `drop --version`
then make sure to run 
`drop update` from your working directory (`/gpfs/scratch/drop/`)

Then could you please run the same command we talked about earlier?
`snakemake /gpfs/scratch/drop/root/processed_data/mae/allelic_counts/QC--UDP-1003_RNA.csv.gz --cores 1`

I just want to make sure things have been updated correctly.

**Comment by gevro** [comment] 2021-07-26 13:17
1) Yes, I have upgraded to DROP 1.1.0 and confirmed with drop --version:
```
drop, version 1.1.0
```

2) There is no need to run drop update. I started a new drop folder from the beginning with 'drop init'.

3) The output of this command 'snakemake /gpfs/scratch/drop/root/processed_data/mae/allelic_counts/QC--UDP-1003_RNA.csv.gz --cores 1':
```
UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmplhsx3p73

Building DAG of jobs...
WorkflowError in line 52 of /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile:
Function did not return str or list of str.
```

4) I am not updated or touching sample_annotation.tsv in any way. I don't know why DROP keeps saying 'Updating to current Sample Annotation'. It must be a bug in drop.

5) I will write to smith@in.tum.de to continue the conversation.

**Comment by mumichae** [comment] 2021-07-26 17:11
Please use the `--debug` flag for the error message

**Comment by nickhsmith** [comment] 2021-07-27 07:28
Solved offline, there was a problem with the conda environment. We determined this after attempting to run the demo, and the user managed to solve the issues by fixing a python conflict.

**Closed as completed by nickhsmith** 2021-07-27 07:28 UTC
