### ISSUE TITLE
mae pipeline failing

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#153] opened 2020-12-29 18:29 UTC
Hi,
I'm getting this error:
```
[Tue Dec 29 13:24:59 2020]
rule MonoallelicExpression_pipeline_MAE_deseq_mae_R:
    input: /gpfs/scratch/evrong01/droptest3/root/processed_data/mae/allelic_counts/UDP-1201.exome--UDP-1201_RNA.csv.gz, Scripts/MonoallelicExpression/pipeline/MAE/deseq_mae.R
    output: /gpfs/scratch/evrong01/droptest3/root/processed_results/mae/samples/UDP-1201.exome--UDP-1201_RNA_res.Rds
    log: /gpfs/scratch/evrong01/droptest3/.drop/tmp/MAE/deseq/UDP-1201.exome--UDP-1201_RNA.Rds
    jobid: 12
    wildcards: vcf=UDP-1201.exome, rna=UDP-1201_RNA

Started with deseq
[1] "Running DESeq..."
Error in DESeqDataSet(se, design = design, ignoreRank) : 
  counts matrix should be numeric, currently it has mode: logical
Calls: DESeq4MAE ... deseq_for_allele_specific_expression -> DESeqDataSetFromMatrix -> DESeqDataSet
Execution halted
[Tue Dec 29 13:25:14 2020]
Error in rule MonoallelicExpression_pipeline_MAE_deseq_mae_R:
    jobid: 12
    output: /gpfs/scratch/evrong01/droptest3/root/processed_results/mae/samples/UDP-1201.exome--UDP-1201_RNA_res.Rds
    log: /gpfs/scratch/evrong01/droptest3/.drop/tmp/MAE/deseq/UDP-1201.exome--UDP-1201_RNA.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 283 of /tmp/tmpsnxx9r0e:
Command 'set -euo pipefail;  Rscript --vanilla /gpfs/scratch/evrong01/droptest3/.snakemake/scripts/tmpn85jcvs8.deseq_mae.R' returned non-zero exit status 1.
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/tmp/tmpsnxx9r0e", line 283, in __rule_MonoallelicExpression_pipeline_MAE_deseq_mae_R
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
```

I think it's the same as #133

**Comment by vyepez88** [comment] 2021-02-10 09:40
yes, it's the same as #133 . Can you please check the answer that we provided there?

**Comment by mumichae** [comment] 2021-02-10 11:15
This seems to be a duplicate of #133, please check there for updates.

**Closed as completed by mumichae** 2021-02-10 11:15 UTC
