### ISSUE TITLE
Miscellaneous warnings

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#78] opened 2020-06-24 17:08 UTC
I'm getting a few various warnings for snakemake aberrantExpression.
Please advise.

1) Warning 1:
output file: /tmp/RtmpqpfsOK/file47f182f1fc6fa/Datasets.knit.md

/gpfs/share/apps/pandoc/2.2.3.2/bin/pandoc +RTS -K512m -RTS /tmp/RtmpqpfsOK/file47f182f1fc6fa/Datasets.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/RtmpqpfsOK/file47f18539284e
5/Scripts_Counting_Datasets.html --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 --variable toc_smoot
h_scroll=1 --variable toc_print=1 --template /gpfs/data/bin/Gilad/R/libs/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --css lib/add_content_table.css --css lib/leo_style.css --variable 'them
e:bootstrap' --include-in-header /tmp/RtmpqpfsOK/rmarkdown-str47f187a527639.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /gpfs/data/
/bin/Gilad/R/libs/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /gpfs/data/bin/Gilad/R/libs/rmarkdown/rmd/lua/latex-div.lua --variable code_folding=hide --variable source_embed=Datasets.R --include-after-body /tmp/R
tmpqpfsOK/file47f187c2684bf.html --variable code_menu=1 
[WARNING] Could not parse YAML metadata at line 1 column 1: :9:121: Unexpected '
  '
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Datasets.utf8'

Output created: /tmp/RtmpqpfsOK/file47f18539284e5/Scripts_Counting_Datasets.html

2) Warning 2: Note: I have X11 configured. I'm not sure why this is saying this.
Output created: /tmp/RtmpY461CM/file480162435d245/Summary_GTEX100.html
Warning messages:
1: In grDevices::png(f) : unable to open connection to X11 display ''
2: Transformation introduced infinite values in continuous y-axis 
3: Removed 62 rows containing missing values (geom_bar). 
[1] TRUE TRUE TRUE TRUE
[Wed Jun 24 10:45:12 2020]
Finished job 9.
101 of 104 steps (97%) done

3) Warning 3: 
Warning message:
In OutriderDataSet(counts) :
  No sampleID was specified. We will generate a generic one.
47762 genes did not pass the filter. This is 78.8% of the genes.
[Wed Jun 24 07:25:52 2020]
Finished job 10.
96 of 104 steps (92%) done

4) Warning 4:
Output created: /tmp/Rtmp6qybWF/file3d75e19e5acf9/Summary_GTEX100.html
Warning messages:
1: In grDevices::png(f) : unable to open connection to X11 display ''
2: Transformation introduced infinite values in continuous x-axis 
3: Removed 14236 rows containing non-finite values (stat_bin). 
4: Transformation introduced infinite values in continuous x-axis 
5: Removed 14236 rows containing non-finite values (stat_density). 

5) Warning 5:
/gpfs/share/apps/pandoc/2.2.3.2/bin/pandoc +RTS -K512m -RTS /tmp/RtmpT3Evl2/file4812b3d242953/Datasets.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/RtmpT3Evl2/file4812b61d64465/Scripts_OUTRIDER_Datasets.html --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --css lib/add_content_table.css --css lib/leo_style.css --variable 'theme:bootstrap' --include-in-header /tmp/RtmpT3Evl2/rmarkdown-str4812b133c5d3.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/lua/latex-div.lua --variable code_folding=hide --variable source_embed=Datasets.R --include-after-body /tmp/RtmpT3Evl2/file4812b18abd38e.html --variable code_menu=1 
[WARNING] Could not parse YAML metadata at line 1 column 1: :8:122: Unexpected '
  '
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Datasets.utf8'

Output created: /tmp/RtmpT3Evl2/file4812b61d64465/Scripts_OUTRIDER_Datasets.html
Warning message:
In grDevices::png(f) : unable to open connection to X11 display ''

**Comment by vyepez88** [comment] 2020-06-26 01:10
1, 5: We use wBuild on top of Rmarkdown which needs a header (whose entries begin with `#'`) that gets parsed and transformed into the metadata for the Rmarkdown. Nevertheless, Rmarkdown doesn't recognize this header directly, so it complains that it begins with a ' character, and that there's no title element, although there is one through wBuild.
This is how the beginning of the header looks like:
```
#'---
#' title: Counts Overview
```
2,4: I'm not sure about the X11 warning, I was not able to reproduce it. Can you please check that your Summary html has the same plots as: https://www.cmm.in.tum.de/public/paper/drop_analysis/webDir/html/AberrantExpression/Counting/v29/Summary_all.html
The other warnings are from ggplot saying that some values are lost when we log-transform them

3: This is a warning from OUTRIDER saying that you didn't specify a name for the column containing the sample ids, and it will name it 'sampleID'. I will fix it in DROP.

**Comment by gevro** [comment] 2020-06-26 02:49
2,4 - No, some plots are blank. See here for my output: https://www.dropbox.com/sh/yat2meihcadjubb/AAA7Zjje-aKAHPgwMtyDQT2oa?dl=0

3 - What do you mean that I didn't specif a name for sample ids? My samples tsv file has RNA_ID and DNA_ID columns. In your help file, it doesn't specify to add a column sampleID: https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html
Do I also need to add a sampleID column?

**Comment by gevro** [comment] 2020-06-26 18:51
Also, regarding 2,4 - why is X11 required by DROP? It should not require X11, because if the pipeline is run on a compute node in a computing cluster, it won't have X11. X11 is only for interactive shells and local R processes. X11 should not be required for making plots.

**Comment by vyepez88** [comment] 2020-06-26 20:01
2,4 The plots were created, but they are blank due to the content. Can you please check the <root>/processed_data/aberrant_expression/{geneAnnotation}/coverage folder? Do the file names correspond to your RNA_IDs? Then check the file <root>/processed_data/aberrant_expression/{geneAnnotation}/outrider/{DROP_GROUP}/bam_coverage.tsv. It should contain a column with the RNA_IDs and another with the total counts.
Finally, check your count matrix: <root>/processed_data/aberrant_expression/{geneAnnotation}/outrider/{DROP_GROUP}/total_counts.Rds. Do the column names correspond to your RNA_IDs?
3, You don't need a sampleID column. OUTRIDER wants to know which column contains the sample ID. If you don't provide a column name, it will take the column names from the count matrix, which correspond to the RNA_ID from the sample annotation. Inside DROP, I didn't tell this explicitly, but I fixed it already, so the warning shouldn't appear anymore.

**Comment by gevro** [comment] 2020-06-26 22:34
Yes - the coverage folder contains file names corresponding to my RNA_IDs. Here is the content of one file:
#cat GTEX-111YS_RNA.tsv
GTEX-111YS_RNA	157776313

Yes - bam_coverage.tsv contains the correct info:
#head bam_coverage.tsv
sampleID	record_count
GTEX-11EMC_RNA	330330113
GTEX-11VI4_RNA	175454873
GTEX-11TUW_RNA	99756241
GTEX-12ZZX_RNA	195079291

total_counts.Rds - I don't know how to examine this file. In R it shows me only this:
class: RangedSummarizedExperiment 
dim: 60609 107 
metadata(0):
assays(1): counts
rownames(60609): ENSG00000000003.15 ENSG00000000005.6 ...
  ENSG00000288484.1 ENSG00000288520.1
rowData names(0):
colnames: NULL
colData names(9): RNA_ID DNA_ID ... COUNT_OVERLAPS DNA_VCF_FILE

head(assay(blah))
                    [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
ENSG00000000003.15     3     6   124     9    15     3    10     9     2     9
ENSG00000000005.6      0     0     0     0     1     0     2     1     0     0
ENSG00000000419.12    47   222  9232   354   136   316   164   393   643   254
ENSG00000000457.14   150   349  5524   748   602   482   237   578   466   396
ENSG00000000460.17    68    80  1872   192   180   108    80   134   133   175
ENSG00000000938.13 15494 29859 75695 67736 20156 40715 22830 82117 51862 16375

> colData(blah)
DataFrame with 107 rows and 9 columns
            RNA_ID      DNA_ID      DROP_GROUP
       <character> <character>     <character>
1   GTEX-11DYG_RNA  GTEX-11DYG GTEX100,GTEXALL
2   GTEX-11ZTT_RNA  GTEX-11ZTT GTEX100,GTEXALL
3     UDP-1103_RNA     1917856 GTEX100,GTEXALL
4   GTEX-13CZU_RNA  GTEX-13CZU GTEX100,GTEXALL
5   GTEX-12WSH_RNA  GTEX-12WSH GTEX100,GTEXALL
...            ...         ...             ...
103 GTEX-1339X_RNA  GTEX-1339X GTEX100,GTEXALL
104 GTEX-1212Z_RNA  GTEX-1212Z GTEX100,GTEXALL
105 GTEX-12WSM_RNA  GTEX-12WSM GTEX100,GTEXALL
106 GTEX-1122O_RNA  GTEX-1122O GTEX100,GTEXALL
107 GTEX-11ZU8_RNA  GTEX-11ZU8 GTEX100,GTEXALL

                                                                                        RNA_BAM_FILE
                                                                                          <character>
1   /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11DYG-0006-SM-5NQB2.Aligned.sortedByCoord.out.patched.md.bam
2   /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11ZTT-0006-SM-5N9FX.Aligned.sortedByCoord.out.patched.md.bam
3                                                 /gpfs/scratch/evrong01/UDP-RNA_seq/UDP-1103_RNA.bam
4   /gpfs/scratch/evrong01/GTEX/BAM/GTEX-13CZU-0005-SM-5LU8K.Aligned.sortedByCoord.out.patched.md.bam
5   /gpfs/scratch/evrong01/GTEX/BAM/GTEX-12WSH-0005-SM-5NQ9P.Aligned.sortedByCoord.out.patched.md.bam
...                                                                                               ...
103 /gpfs/scratch/evrong01/GTEX/BAM/GTEX-1339X-0005-SM-5O9CQ.Aligned.sortedByCoord.out.patched.md.bam
104 /gpfs/scratch/evrong01/GTEX/BAM/GTEX-1212Z-0006-SM-5NQ8M.Aligned.sortedByCoord.out.patched.md.bam
105 /gpfs/scratch/evrong01/GTEX/BAM/GTEX-12WSM-0005-SM-5NQB3.Aligned.sortedByCoord.out.patched.md.bam
106 /gpfs/scratch/evrong01/GTEX/BAM/GTEX-1122O-0005-SM-5O99J.Aligned.sortedByCoord.out.patched.md.bam
107 /gpfs/scratch/evrong01/GTEX/BAM/GTEX-11ZU8-0005-SM-5PNU5.Aligned.sortedByCoord.out.patched.md.bam
    PAIRED_END      STRAND         COUNT_MODE COUNT_OVERLAPS
     <logical> <character>        <character>      <logical>
1         TRUE          no IntersectionStrict           TRUE
2         TRUE          no IntersectionStrict           TRUE
3         TRUE          no IntersectionStrict           TRUE
4         TRUE          no IntersectionStrict           TRUE
5         TRUE          no IntersectionStrict           TRUE
...        ...         ...                ...            ...
103       TRUE          no IntersectionStrict           TRUE
104       TRUE          no IntersectionStrict           TRUE
105       TRUE          no IntersectionStrict           TRUE
106       TRUE          no IntersectionStrict           TRUE
107       TRUE          no IntersectionStrict           TRUE
                                                                                                  DNA_VCF_FILE
                                                                                                   <character>
1   /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
2   /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
3                            /gpfs/data/evronylab/NYU-UDP/variants/UDP-1100/WES.SNVINDEL/UDP-1103_exome.vcf.gz
4   /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
5   /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
...                                                                                                        ...
103 /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
104 /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
105 /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
106 /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
107 /gpfs/scratch/evrong01/GTEX/VCF/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz

> rowData(blah)
DataFrame with 60609 rows and 0 columns

**Comment by vyepez88** [comment] 2020-06-29 01:05
the coverage files look good. It seems that the colnames of the total_counts are null. Can you please check the script at <project>/.drop/modules/aberrant-expression-pipeline/Scripts/Counting/mergeCounts.R?
In line 60 it should have: rownames(colData(total_counts)) <- colData(total_counts)$RNA_ID
If it doesn't have that line, can you please update DROP?

**Comment by gevro** [comment] 2020-06-29 01:56
This is the code from my version of mergeCounts.R. But I just updated drop a few days ago. Did something change recently? How do I make sure I always have the latest version, since they are updating very frequently.

     47 # total_counts <- do.call(cbind, counts_list)
     48 colnames(total_counts) <- names(counts_list)
     49 rownames(total_counts) <- rownames(counts_list[[1]])
     50 rowRanges(total_counts) <- rowRanges(counts_list[[1]])
     51 
     52 # Add sample annotation data (colData)
     53 sample_anno <- fread(snakemake@config$sampleAnnotation)
     54 sample_anno <- sample_anno[, .SD[1], by = RNA_ID]
     55 col_data <- data.table(RNA_ID = colnames(total_counts))
     56 col_data <- left_join(col_data, sample_anno, by = "RNA_ID")
     57 rownames(col_data) <- col_data$RNA_ID
     58 colData(total_counts) <- as(col_data, "DataFrame")
     59 
     60 saveRDS(total_counts, snakemake@output$counts)

**Comment by mumichae** [comment] 2020-06-29 05:17
How do you usually update? Don't forget to use `drop update` in your project directory to update the submodule code. Updating the repository is not enough for these changes to apply to your specific project.

**Comment by gevro** [comment] 2020-06-29 17:06
That must be the problem! Ok, I will try again.

**Comment by gevro** [comment] 2020-06-29 17:09
Would it help if you add 'drop update' to be automatic when running the pipeline?
Also, see my prior recommendation for a snakemake command to completely clear the prior computation of a pipeline because snakemake -F, -f, and -r don't always work.

**Comment by gevro** [comment] 2020-06-29 17:38
After running drop update, the pipeline doesn't work anymore at all:
Error: Snakefile "/gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-expression-pipeline/Snakefile" not found.
I only have the .drop/modules/helpers folder.

**Comment by gevro** [comment] 2020-06-29 17:44
snakemake aberrantExpression --cores 2

I also tried to make a new folder (drop init) and still getting the same error:
Structuring dependencies...
Dependencies file generated.

Building DAG of jobs...
Executing subworkflow AE.
Error: Snakefile "/gpfs/scratch/evrong01/drop100test/.drop/modules/aberrant-expression-pipeline/Snakefile" not found.

**Comment by vyepez88** [comment] 2020-06-29 18:20
that's weird, can you please check if indeed that Snakefile does not exist?
if so, you can download it from here: https://github.com/mumichae/aberrant-expression-pipeline/blob/c10b2dcdf8413f5392e5f8c85fb807536d3d1c0a/Snakefile and put it in the directory specified in the error.

**Comment by gevro** [comment] 2020-06-29 23:35
It definitely doesn't exist:
#ls /gpfs/scratch/evrong01/drop100test/.drop/modules/aberrant-expression-pipeline/Snakefile
ls: cannot access /gpfs/scratch/evrong01/drop100test/.drop/modules/aberrant-expression-pipeline/Snakefile: No such file or directory

#ls .drop/modules
helpers

I don't want to download the snakefile, because what is the solution to this problem? I created a new folder with 'drop init', so I'm not sure what is happening. I want to be able to run the pipeline.

See here: drop init is not making the correct snakefiles:

[evrong01@bigpurple-ln3 scratch]$ mkdir droptest
[evrong01@bigpurple-ln3 scratch]$ cd droptest/
[evrong01@bigpurple-ln3 droptest]$ drop init
init...done
[evrong01@bigpurple-ln3 droptest]$ ls .drop/modules/
helpers

**Comment by mumichae** [comment] 2020-06-30 02:24
> Would it help if you add 'drop update' to be automatic when running the pipeline?
the idea is, that the user shouldn't be updating drop ob a regular basis. But this is currently the case, as we are still fixing and including new features.
> Also, see my prior recommendation for a snakemake command to completely clear the prior computation of a pipeline because snakemake -F, -f, and -r don't always work.
I'm currently working on fixing that problem. I wanted to address it for s while now, but the submodule structure makes things a bit more difficult than plain snakemake. There will be bigger internal changes, so it'll take some time until things will be working as desired. I'll let you know once that feature has been fixed.

**Comment by mumichae** [comment] 2020-06-30 02:27
> After running drop update, the pipeline doesn't work anymore at all:
> Error: Snakefile "/gpfs/scratch/evrong01/droptest/.drop/modules/aberrant-expression-pipeline/Snakefile" not found.
> I only have the .drop/modules/helpers folder.

This usually happens, when the git repository has not been cloned recursively, as we are using submodules. Try initialising the submodules in your local drop repo with `git submodule update --init --recursive`. Check if you have 3 submodules in `drop/modules/`
Assuming you installed with `pip install -e <path/to/drop/repo/root/>`, you don't have to reinstall the python package. Otherwise, I recommend the command with `-e`, while we are still updating drop. (This will link your package to the source code location, and you don't have to reinstall after updating the repo)
Finally, update your project directory again with `drop update`. Check the .drop folder to see if you have your submodules and that the folders aren't empty

**Comment by gevro** [comment] 2020-06-30 02:48
Thanks. This fixed it.

**Comment by gevro** [comment] 2020-07-02 17:45
> Also, regarding 2,4 - why is X11 required by DROP? It should not require X11, because if the pipeline is run on a compute node in a computing cluster, it won't have X11. X11 is only for interactive shells and local R processes. X11 should not be required for making plots.

Any update about X11 and DROP? It shouldn't be using X11 since it is not an interactive pipeline.

**Comment by mumichae** [comment] 2020-07-06 04:20
X11 is used by default for saving png files. It might be possible to switch to cairo, but we'd need to apply it to every single script. @kTakumo What is your take on it for the wbuild Rmarkdown files?

**Comment by gevro** [comment] 2020-07-06 14:18
I see. Yes I think you should probably switch because most people are not going to be running drop with an interactive shell. Rather, they will be submitting it as a job on a computing cluster. And submitted jobs will never have X11...

I just ran the latest version of drop and got these warnings again:

output file: /tmp/RtmpjqwQMN/file22338354f8f35/Datasets.knit.md

/gpfs/share/apps/pandoc/2.2.3.2/bin/pandoc +RTS -K512m -RTS /tmp/RtmpjqwQMN/file22338354f8f35/Datasets.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/R
tmpjqwQMN/file22338607d6ad9/Scripts_OUTRIDER_Datasets.html --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h
2,h3 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/h/default.html --no-highlight --variable highligh
tjs=1 --css lib/add_content_table.css --css lib/leo_style.css --variable 'theme:bootstrap' --include-in-header /tmp/RtmpjqwQMN/rmarkdown-str22338346f6370.html --mathjax --variable 'mathjax-url:https
://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /gpfs/data/evronylab/bin/Gilad/
R/libs/rmarkdown/rmd/lua/latex-div.lua --variable code_folding=hide --variable source_embed=Datasets.R --include-after-body /tmp/RtmpjqwQMN/file22338214d7615.html --variable code_menu=1 

Output created: /tmp/RtmpjqwQMN/file22338607d6ad9/Scripts_OUTRIDER_Datasets.html
Warning message:
In grDevices::png(f) : unable to open connection to X11 display ''
[1] TRUE TRUE TRUE
[Sun Jul  5 01:05:46 2020]
Finished job 5.
225 of 227 steps (99%) done


----

output file: /tmp/RtmpL6pOVO/file222256c8f40f2/Summary.knit.md

/gpfs/share/apps/pandoc/2.2.3.2/bin/pandoc +RTS -K512m -RTS /tmp/RtmpL6pOVO/file222256c8f40f2/Summary.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/Rt
mpL6pOVO/file222256b2d8651/Summary_GTEX100.html --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --vari
able toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --css
 lib/add_content_table.css --css lib/leo_style.css --variable 'theme:bootstrap' --include-in-header /tmp/RtmpL6pOVO/rmarkdown-str2222524abade6.html --mathjax --variable 'mathjax-url:https://mathjax.
rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmar
kdown/rmd/lua/latex-div.lua --variable code_folding=hide --variable source_embed=Summary.R --include-after-body /tmp/RtmpL6pOVO/file222255db93aff.html --variable code_menu=1 

Output created: /tmp/RtmpL6pOVO/file222256b2d8651/Summary_GTEX100.html
Warning messages:
1: In grDevices::png(f) : unable to open connection to X11 display ''
2: Transformation introduced infinite values in continuous y-axis 
3: Removed 63 rows containing missing values (geom_bar). 
[1] TRUE TRUE TRUE TRUE


----

output file: /tmp/RtmpcDfm7w/file1766c73ebd06f/Summary.knit.md

/gpfs/share/apps/pandoc/2.2.3.2/bin/pandoc +RTS -K512m -RTS /tmp/RtmpcDfm7w/file1766c73ebd06f/Summary.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/Rt
mpcDfm7w/file1766c31634e37/Summary_GTEX100.html --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --vari
able toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --css
 lib/add_content_table.css --css lib/leo_style.css --variable 'theme:bootstrap' --include-in-header /tmp/RtmpcDfm7w/rmarkdown-str1766c11242c58.html --mathjax --variable 'mathjax-url:https://mathjax.
rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /gpfs/data/evronylab/bin/Gilad/R/libs/rmar
kdown/rmd/lua/latex-div.lua --variable code_folding=hide --variable source_embed=Summary.R --include-after-body /tmp/RtmpcDfm7w/file1766c772ecd82.html --variable code_menu=1 

Output created: /tmp/RtmpcDfm7w/file1766c31634e37/Summary_GTEX100.html
Warning messages:
1: In grDevices::png(f) : unable to open connection to X11 display ''
2: Transformation introduced infinite values in continuous x-axis 
3: Removed 14236 rows containing non-finite values (stat_bin). 
4: Transformation introduced infinite values in continuous x-axis 
5: Removed 14236 rows containing non-finite values (stat_density). 
[1] TRUE TRUE TRUE TRUE

---
Warning message:
In OutriderDataSet(counts) :
  No sampleID was specified. We will generate a generic one.
47762 genes did not pass the filter. This is 78.8% of the genes.
[Sat Jul  4 21:46:26 2020]
Finished job 10.

**Comment by gevro** [comment] 2020-07-06 14:21
> 3, You don't need a sampleID column. OUTRIDER wants to know which column contains the sample ID. If you don't provide a column name, it will take the column names from the count matrix, which correspond to the RNA_ID from the sample annotation. Inside DROP, I didn't tell this explicitly, but I fixed it already, so the warning shouldn't appear anymore.

Note: this error still appears in the latest version of drop (updated a few days ago).

Warning message:
In OutriderDataSet(counts) :
  No sampleID was specified. We will generate a generic one.
47762 genes did not pass the filter. This is 78.8% of the genes.
[Sat Jul  4 21:46:26 2020]
Finished job 10.

**Comment by vyepez88** [comment] 2020-07-06 16:13
It's not an error, but a warning. It's fixed now in the **take as sample ID the RNA ID** commit https://github.com/mumichae/aberrant-expression-pipeline/tree/f5d1920f4df95dc5863ca0779dd48deff03e2493/Scripts/Counting

**Closed as completed** 2020-10-21 13:31 UTC
