### ISSUE TITLE
Sample annotation read error

### ISSUE THREAD

**Issue by mumichae** [gagneurlab/drop#127] opened 2020-11-03 12:56 UTC
Quoted from #126

Thank you for your effort. The latest fix enables me to run the one line sample -which fails as expected as <10 samples are valid.
The demo also runs through.

The fix is not perfect though: My unmodified sample.tsv fails at chunck 4:

> label: unnamed-chunk-4
> Quitting from lines 55-59 (/tmp/RtmpVqDpzK/file31d93c581568/SampleAnnotation.spin.Rmd)
> Error in .checkTypos(e, names_x) :
>   Object 'RNA_ID' not found amongst I18R008Rf02, /mnt/breast_cancer/cinder_backups/qmrkh_data/bam/Probe/I18R008Rf02/QMRKH078AP_I18R008Rf02_accepted_hits.bam, /mnt/breast_cancer/QMRKH/results/0031-1/Annotation/0031-1/VEP/Strelka_I18D015a01_variants_VEP.ann.vcf.gz, I18D015a01, outrider,mae,fraser,blood and 8 more

But: removing the additional tabs at the end enables me to run sampleAnnotation successfully.

Edit: I'm currently using github.com/mumichae/drop.git@fix_import_counts 7f41259

_Originally posted by @nicweb in https://github.com/gagneurlab/drop/issues/126#issuecomment-721094396_

**Comment by mumichae** [comment] 2020-11-04 04:16
Could you provide more output so we can see which snakemake rule causes the error?
Just run the pipeline with a single core to ensure that the output is pure,

**Comment by mumichae** [comment] 2020-11-04 08:24
Make sure you can read your sample annotation file in R using `data.table`.
```
library(data.table)
fread("sample_annotation.tsv")
```
It seems as though the header column is missing or not read correctly.

**Comment by nicweb** [comment] 2020-11-05 09:00
I modified the original file. At the moment I'm unable to reproduce the error, even after re-adding additional tabs at the end.
One question regarding the HPO column: is this a mandatory column?

**Comment by mumichae** [comment] 2020-11-07 05:15
Glad it worked, let me know if you encounter this problem again. For now I'll be closing this issue.

Regarding the HPO column: No, it is not mandatory. @vyepez88 Could you clarify on the documentation?

**Comment by nicweb** [comment] 2020-11-10 08:20
That's weird... Depending on your definition of mandatory: I remember the pipeline fails for me when the column is empty.
I'll try to provide a minimal example

**Comment by vyepez88** [comment] 2020-11-12 21:19
Hi, we meant 'not mandatory' in the sense that the pipeline ran if the column was not present. But, it failed if it was present and all blank. This is fixed now in the dev branch.

**Closed as completed** 2020-11-13 18:51 UTC
Labels: question
